workflows:
  android-debug:
    name: Android Debug Build
    max_build_duration: 120
    environment:
      flutter: stable
    scripts:
      - name: Get dependencies
        script: |
          cd mobile
          flutter pub get
      - name: Build Android Debug APK
        script: |
          cd mobile
          flutter build apk --debug
          mv build/app/outputs/flutter-apk/app-debug.apk build/app/outputs/flutter-apk/Monetra.apk
    artifacts:
      - mobile/build/**/outputs/**/*.apk
